version: '3.8'

services:
  client:
    build: ./client
    ports:
      - "8080:80"
    depends_on:
      - server
    networks:
      - app-network

  server:
    build: ./server
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
    networks:
      - app-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "${REDIS_PASSWORD}"]

networks:
  app-network:
    driver: bridge

volumes:
  redis-data:
